"""add clusters tables and cluster_id to extractions

Revision ID: 3886a0f27cf2
Revises: ca48b40b7096
Create Date: 2026-03-22 21:09:36.159572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3886a0f27cf2'
down_revision: Union[str, None] = 'ca48b40b7096'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clusters',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cluster_accounts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('cluster_id', sa.String(length=36), nullable=False),
    sa.Column('platform', sa.Enum('youtube', 'tiktok', 'instagram', name='platform'), nullable=False),
    sa.Column('handle', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['clusters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cluster_id', 'platform', 'handle', name='uq_cluster_platform_handle')
    )
    op.create_table('account_posts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('clip_id', sa.String(length=36), nullable=True),
    sa.Column('platform_post_id', sa.String(length=500), nullable=True),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.Column('likes', sa.Integer(), nullable=False),
    sa.Column('comments', sa.Integer(), nullable=False),
    sa.Column('shares', sa.Integer(), nullable=False),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['cluster_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['clip_id'], ['clips.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    bind = op.get_bind()
    if bind.dialect.has_table(bind, 'posting_queue_items'):
        op.drop_table('posting_queue_items')
    op.add_column('clip_extractions', sa.Column('cluster_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_clip_extractions_cluster_id'), 'clip_extractions', ['cluster_id'], unique=False)
    # SQLite does not support ALTER TABLE ADD CONSTRAINT; FK is declared in the model but not enforced at DB level.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clip_extractions_cluster_id'), table_name='clip_extractions')
    op.drop_column('clip_extractions', 'cluster_id')
    op.create_table('posting_queue_items',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('job_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('status', sa.VARCHAR(length=7), nullable=False),
    sa.Column('position', sa.INTEGER(), nullable=False),
    sa.Column('caption_text', sa.TEXT(), nullable=True),
    sa.Column('posted_at', sa.DATETIME(), nullable=True),
    sa.Column('error_message', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('account_posts')
    op.drop_table('cluster_accounts')
    op.drop_table('clusters')
    # ### end Alembic commands ###
