"""add dubbing_jobs and dubbing_outputs tables

Revision ID: 696e2288e247
Revises: 7b7f824fed22
Create Date: 2026-03-25 23:02:52.027111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '696e2288e247'
down_revision: Union[str, None] = '7b7f824fed22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dubbing_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('source_video_key', sa.String(length=500), nullable=False),
    sa.Column('source_url', sa.String(length=2048), nullable=True),
    sa.Column('languages', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'downloading', 'processing', 'completed', 'failed', name='dubbingjobstatus'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('credits_charged', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dubbing_outputs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('dubbing_job_id', sa.String(length=36), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('elevenlabs_dubbing_id', sa.String(length=255), nullable=True),
    sa.Column('dubbed_audio_key', sa.String(length=500), nullable=True),
    sa.Column('synclabs_video_id', sa.String(length=255), nullable=True),
    sa.Column('output_video_key', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('pending', 'dubbing', 'lip_syncing', 'completed', 'failed', name='dubbingoutputstatus'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['dubbing_job_id'], ['dubbing_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dubbing_outputs')
    op.drop_table('dubbing_jobs')
    # ### end Alembic commands ###
