"""add clip_extractions and clips tables

Revision ID: ca48b40b7096
Revises: 60e4fa57da22
Create Date: 2026-03-22 13:32:05.066397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca48b40b7096'
down_revision: Union[str, None] = '60e4fa57da22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clip_extractions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('pending', 'downloading', 'transcribing', 'analyzing', 'extracting', 'completed', 'failed', name='extractionstatus'), nullable=False),
    sa.Column('youtube_url', sa.String(length=2048), nullable=False),
    sa.Column('video_title', sa.String(length=500), nullable=True),
    sa.Column('video_duration', sa.Float(), nullable=True),
    sa.Column('source_video_key', sa.String(length=500), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('credits_charged', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clips',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('extraction_id', sa.String(length=36), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('start_time', sa.Float(), nullable=False),
    sa.Column('end_time', sa.Float(), nullable=False),
    sa.Column('duration', sa.Float(), nullable=False),
    sa.Column('virality_score', sa.Integer(), nullable=False),
    sa.Column('hook_text', sa.Text(), nullable=False),
    sa.Column('transcript_text', sa.Text(), nullable=False),
    sa.Column('reframed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['extraction_id'], ['clip_extractions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clips')
    op.drop_table('clip_extractions')
    # ### end Alembic commands ###
