"""add profile_snapshots table

Revision ID: e36740bce5d5
Revises: f0458e10c260
Create Date: 2026-03-22 22:12:52.370541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e36740bce5d5'
down_revision: Union[str, None] = 'f0458e10c260'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('followers', sa.Integer(), nullable=False),
    sa.Column('following', sa.Integer(), nullable=False),
    sa.Column('total_likes', sa.BigInteger(), nullable=False),
    sa.Column('total_videos', sa.Integer(), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('recent_videos', sa.JSON(), nullable=True),
    sa.Column('scraped_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['cluster_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_profile_snapshots_account_scraped', 'profile_snapshots', ['account_id', 'scraped_at'], unique=False)
    # SQLite does not enforce FK constraints; spurious FK detections for account_posts and
    # clip_extractions are omitted — they were already declared in the model layer and
    # do not need a separate ALTER TABLE in SQLite.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_profile_snapshots_account_scraped', table_name='profile_snapshots')
    op.drop_table('profile_snapshots')
    # ### end Alembic commands ###
